name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov coverage-badge
        
    - name: Run tests with coverage
      run: |
        pytest --cov=. --cov-report=term-missing
        
    - name: Generate coverage badge
      run: |
        coverage-badge -o coverage.svg -f
        
    - name: Commit coverage badge
      if: github.ref == 'refs/heads/main'
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add coverage.svg
          git commit -m "Update coverage badge"
          git push
        fi
